apiVersion: v1
kind: Pod
metadata:
  name: postgres-client-house
  namespace: {{ .Values.namespace.name }}
spec:
  containers:
  - name: kubectl-psql
    image: postgres
    command:
    - sleep
    - "3600"
